title: LM
description: Software engineer focused on building web applications.
url: "https://www.mendelowski.com"
ga_tracking: UA-134628913-1
permalink: pretty

remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links:
  GitHub: https://github.com/lowski
  Twitter: https://twitter.com/lowski_
